import { useState } from 'react';
import { BookOpen, ChevronDown, ExternalLink, GitBranch, MoreHorizontal, RotateCcw } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { ConfirmationDialog } from './confirmation-dialog';
import data from '@/fixtures/overview.json';
export function DeploymentCard({ onAction }: { onAction: (message: string) => void }) {
  const [rollbackOpen, setRollbackOpen] = useState(false);
  return <Card><CardHeader><CardTitle>Production deployment</CardTitle><div className="ds-row"><Button size="sm" variant="outline" onClick={() => onAction('Repository connection is an example action. No account was connected.')}>Connect Git</Button><Button size="sm" variant="outline" className="ds-hide-mobile" onClick={() => setRollbackOpen(true)}><RotateCcw aria-hidden="true" />Instant rollback</Button><div className="ds-split"><Button size="sm" onClick={() => onAction('Preview selected. This example has no live deployment.')}>Visit</Button><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" aria-label="Visit options"><ChevronDown aria-hidden="true" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onAction('Preview opens in the consuming application.')}>Open preview</DropdownMenuItem><DropdownMenuItem onSelect={() => onAction(`Example domain: ${data.domain}`)}>View domain</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label="Project actions"><MoreHorizontal aria-hidden="true" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onAction('Open project settings after the next design review.')}>Project settings</DropdownMenuItem><DropdownMenuItem onSelect={() => setRollbackOpen(true)}>Preview rollback</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></CardHeader>
    <CardContent><div className="ds-deployment-content"><div className="ds-deployment-preview" role="img" aria-label="Neutral deployment preview placeholder"><div className="ds-preview-placeholder">Preview placeholder</div><div className="ds-preview-label" /></div><div className="ds-metadata"><dl><dt>Deployment</dt><dd>{data.deployment}</dd></dl><dl><dt>Domains</dt><dd className="ds-row">{data.domain}<ExternalLink className="ds-icon" aria-hidden="true" /><Badge>+1</Badge></dd></dl><div className="ds-metadata-pair"><dl><dt>Status</dt><dd><span className="ds-status">Ready</span></dd></dl><dl><dt>Created</dt><dd>{data.created} by {data.user}</dd></dl></div><dl><dt>Source</dt><dd><div className="ds-row"><GitBranch className="ds-icon" aria-hidden="true" /><code className="ds-mono">{data.branch}</code></div><div className="ds-row"><code className="ds-mono">{data.commit}</code><span className="ds-small">{data.message}</span></div></dd></dl></div></div></CardContent>
    <Accordion type="single" collapsible><AccordionItem value="settings"><AccordionTrigger><span className="ds-row">Deployment settings<Badge variant="info">3 recommendations</Badge></span></AccordionTrigger><AccordionContent><p className="ds-muted">Use the shared shell, keep semantic tokens, and validate keyboard navigation before publishing a page.</p></AccordionContent></AccordionItem></Accordion>
    <div className="ds-deployment-footer"><p className="ds-muted ds-small">A neutral example built from reusable components. No infrastructure is connected.</p><Button size="sm" variant="outline" onClick={() => onAction('Documentation: start with README.md and docs/README.md.')}><BookOpen aria-hidden="true" />Documentation</Button></div>
    <ConfirmationDialog open={rollbackOpen} onOpenChange={setRollbackOpen} title="Preview rollback?" description="This confirms the interaction pattern only. It will not change a deployment or contact a server." confirmLabel="Confirm preview" onConfirm={() => { setRollbackOpen(false); onAction('Rollback preview confirmed. No deployment was changed.'); }} />
  </Card>;
}
